### ISSUE TITLE
Printing Images from a Python Script

### ISSUE THREAD

**Issue by Zedelghem** [bitrate16/ppa6-python#8]
Have you thought about adding a possibility to print images through your print_service module?

Best
Bj

**Comment by bitrate16** [comment]
It can be done similar to this:

[https://github.com/bitrate16/ppa6-python/blob/2b7ce843a07190c5b441a18247279940020d4780/print-server/__main__.py#L178](url)

```python
# Setup
service = print_service.PrintService(60, 1, 5)
service.start(PRINTER_MAC, PRINTER_MODEL)

# Open
image = PIL.open('image.png')
concentration = 1

# Wrapper
def wrap_print_image(p: ppa6.Printer):
	p.setConcentration(concenttration)
	p.printImage(img)

# Submit
service.add_print_handler(wrap_print_image)
```

Or with labmda

```python
service.add_print_handler(lambda p: p.printImage(PIL.open('image.png'))
```

**Comment by bitrate16** [comment]
Added in commit https://github.com/bitrate16/ppa6-python/commit/d7820b708a551be4dafeff1d78868215d2a489e9, untested

**Comment by Zedelghem** [comment]
Thank you so much! Looking into it right now.
